version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 4567:80
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - ./vw-data:/data
